{% set python_min = '3.10' %}
{% set name = "pymt_soilgrids" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gantian127/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e0338cc33452c087e685edb88401deb2f5c0f3594b1ccd240bb3d2e2876bb25b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - soilgrids >=0.1.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymt_soilgrids

about:
  home: https://github.com/gantian127/pymt_soilgrids
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PyMT plugin for SoilGrids Dataset
  description: |
    pymt_soilgrids is a package that converts soilgrids package into a reusable, 
    plug-and-play data component for PyMT modeling framework. This allows the 
    soil datasets to be easily coupled with other datasets or models that 
    expose a Basic Model Interface.
  doc_url: https://pymt-soilgrids.readthedocs.io/
  dev_url: https://github.com/gantian127/pymt_soilgrids

extra:
  recipe-maintainers:
    - gantian127
